#!/usr/bin/env node

'use strict';
const fs = require('fs');
const os = require('os');
const argv = require('minimist')(process.argv.slice(2));
const slack = require('./slack');
const cfg = require('./helpers/config');
const log = require('./helpers/log');

// setup a help message with all params we handle
let helpMessage = `
--channel | -c    account and channel to send to. e.g. accountNema.channelName
--text    | -t    the text of the slack message to send
--json            text representation of a slack message body to send. See slack docs for format
--help    | -g    this help message.
`
if (argv.help || argv.h) {
  console.log(helpMessage);
  process.exit(0);
}

// make sure that the caller specified an account and channel (e.g. '-channel accountname.channelname')
let channel;
if (argv.c || argv.channel) {
  try {
    channel = argv.channel ? argv.channel : argv.c;
  } catch (e) {
    log.error(`Failed getting account and channel for posting. Did you pass them?\n ${e}`);
    process.exit(-1);
  }
}

const configFilePath = `${os.homedir()}/.raslack/slackConfig.json`;

// get config, setup postbody, post
let config = cfg.load(configFilePath, channel);
let slackPostBody = slack.createPostBody(argv, config);

slack.post(slackPostBody, config)